w10d1/tinyapp_rails/config/routes.rb
Rails.application.routes.draw do
  resources :urls
  # resources :users, except: [:index, :edit]
  resources :users

  get "/register" => "users#new"
  get "/login" => "sessions#new"

  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#new"
end

w10d1/tinyapp_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

w10d1/tinyapp_rails/app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user
end

w10d1/tinyapp_rails/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :urls
end

w10d1/tinyapp_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

w10d1/tinyapp_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # /login
  def new
  end

  # POST new
  def create
    email = params[:email]
    password = params[:password]

    @user = User.find_by_email(email)

    # @user.password == password
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      # redirect_to "/users/#{@user.id}"
      redirect_to urls_path
    else
      redirect_to login_path
    end
  end

  # DELETE
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

w10d1/tinyapp_rails/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]
  before_action :authorize, except: %i[index show] #Allow list

  # GET /urls or /urls.json
  def index
    if current_user
      @urls = current_user.urls
    else
      @urls = Url.all
    end
  end

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls or /urls.json
  def create
    @url = current_user.urls.new(url_params)
    # @url = Url.new(url_params)
    @url.short_url = rand(36**8).to_s(36)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy!

    respond_to do |format|
      format.html { redirect_to urls_path, status: :see_other, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.expect(url: [ :long_url, :description ])
    end
end

w10d1/tinyapp_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ] #Deny list
  before_action :authorize, except: %i[new create] #Allow list

  # GET /users or /users.json
  def index
    @users = User.all
    
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
      # @user = User.find(session[:user_id])
      # @user = @current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :email, :password ])
    end
end

w10d1/tinyapp_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d1/tinyapp_rails/app/helpers/sessions_helper.rb
module SessionsHelper
end

w10d1/tinyapp_rails/app/helpers/urls_helper.rb
module UrlsHelper
end

w10d1/tinyapp_rails/app/helpers/users_helper.rb
module UsersHelper
end

w10d1/tinyapp_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tinyapp Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
  <nav class="navbar navbar-expand-md navbar-dark bg-success">
    <a class="navbar-brand" href="/urls">TinyApp</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="/urls">My URLs</a>
        <a class="nav-item nav-link" href="/urls/new">Create New URL</a>
      </div>
    </div>

    <div>
      <% if current_user %>
      <form style="padding: 0 2em" method="GET" action="/logout">
        <%= current_user.email %>
        <input style="margin-left: 1em" type="submit" value="Logout" />
      </form>
      <%  else  %>

      <div class="navbar-nav">
        <a class="nav-item nav-link" href="/register">Register</a>
        <a class="nav-item nav-link" href="/login">Login</a>
      </div>

      <% end %>
    </div>
  </nav>
</header>

    <main style="margin:1em">
    <%= yield %>
    </main>
  </body>
</html>

w10d1/tinyapp_rails/app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :long_url, style: "display: block" %>
    <%= form.text_field :long_url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

w10d1/tinyapp_rails/app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <p>
    <strong>Short url:</strong>
    <%= url.short_url %>
  </p>

  <p>
    <strong>Long url:</strong>
    <%= url.long_url %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= url.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= url.user_id %>
  </p>

</div>

w10d1/tinyapp_rails/app/views/urls/edit.html.erb
<% content_for :title, "Editing url" %>

<h1>Editing url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Show this url", @url %> |
  <%= link_to "Back to urls", urls_path %>
</div>

w10d1/tinyapp_rails/app/views/urls/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Urls" %>
<h1>Urls</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Short URL</th>
      <th scope="col">Long URL</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
        <% @urls.each do |url| %>
        <tr>
          <td><%= url[:short_url] %></td>
          <td><%= url[:long_url] %></td>
          <td>

            <form method="GET" action="/urls/<%= url[:id] %>">
              <input class="btn btn-outline-primary" type="submit" value="Update" disabled="<%= current_user.nil?%>">
            </form>
          </td>
          <td>
            <form method="DELETE" action="/urls/<%= url[:id] %>">
              <input class="btn btn-outline-danger" type="submit" value="Delete" disabled="<%= current_user.nil?%>">
            </form>
          </td>
        </tr>
        <% end %>
      </tbody>
      </table>

w10d1/tinyapp_rails/app/views/urls/new.html.erb
<% content_for :title, "New url" %>

<h1>New url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Back to urls", urls_path %>
</div>

w10d1/tinyapp_rails/app/views/urls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @url %>

<div>
  <%= link_to "Edit this url", edit_url_path(@url) %> |
  <%= link_to "Back to urls", urls_path %>

  <%= button_to "Destroy this url", @url, method: :delete %>
</div>

w10d1/tinyapp_rails/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

w10d1/tinyapp_rails/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

w10d1/tinyapp_rails/app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

w10d1/tinyapp_rails/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

w10d1/tinyapp_rails/app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

w10d1/tinyapp_rails/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>